### ISSUE TITLE
pass dynamic data on the board

### ISSUE THREAD

**Issue by Vravina** [bear-junior/react-native-draganddrop-board#13]
it is possible to modify the data that is passed to BoardRepository?
After modify data, i have again pass data to BoardRepository but still not able to work drag and drop properly.

can any one give suggestion?

**Comment by zenkhas** [comment]
Make sure the "id" column is set properly in "rows". the ids of card should not repeat in columns and they should start from "1". I have a similar issue because i was using mongo DB's _id column (ObjectID) as id, making it integer fixed the issue for me.

**Comment by TacticCoder** [comment]
With the right setup can be done, refer the readme

**Comment by ariesbrylle-bms** [comment]
Can you show your code on how you fix this @zenkhas ? Thank you.
