### ISSUE TITLE
How to get order index when moving item

### ISSUE THREAD

**Issue by joonhyung** [bear-junior/react-native-draganddrop-board#2]
Hi, I'm trying to make 2D draggable item list, and each item in a list has it's own order.

When I move an item into another column, I can have srcColumnId, destColumnId

but I can't get the moved item's order index in the new destination column,

and also when I change the order in the same column, I can't get the index of new order.

Can you help me to get the information of the source and destination column as it is of course,

and also the **order index of each list**?

Thanks a lot.

**Comment by bear-junior** [comment]
Hi, for now it's only possible to get srcColumnId, destColumnId, draggedItem, you can use onDragEnd function (README), so if you have your destColumnId and draggedItem you can check index for this draggedItem by your own
