### ISSUE TITLE
Cannot update data successfully

### ISSUE THREAD

**Issue by tomasiturralde** [bear-junior/react-native-draganddrop-board#20]
Hi, i've been trying to update the data used by the board with data requested from my API, however the board never updates, and renders nothing as if no data is actually there. I logged the boardRepository to check if it was updated and it was, however the actual board never changed on my app.
The code i'm working on:
![image](https://user-images.githubusercontent.com/22356960/97096334-12430700-1641-11eb-8d9c-d8038ff5de71.png)
![image](https://user-images.githubusercontent.com/22356960/97096337-1c650580-1641-11eb-8191-52f51c5dead7.png)

Any ideas to make this work?

**Comment by TacticCoder** [comment]
Hey, since you use a stateless component, try to put your class definition inside a React state:
`const [boardRepository] = React.useState(new BoardRepository(dummyData));`

**Comment by tomasiturralde** [comment]
Hi again. After trying what you recommended, the result was the same, the updateData method did not refresh the board. So i made a workaround by sending the data to the component through props, and the board uses said data in its constructor, avoiding the update. Thanks for the reply and for the board! It made my life easier

**Comment by ariesbrylle-bms** [comment]
> Hi again. After trying what you recommended, the result was the same, the updateData method did not refresh the board. So i made a workaround by sending the data to the component through props, and the board uses said data in its constructor, avoiding the update. Thanks for the reply and for the board! It made my life easier

Hello, can you share the code for this? Thank you.
