### ISSUE TITLE
Cannot move the board items

### ISSUE THREAD

**Issue by ravi-poonia** [bear-junior/react-native-draganddrop-board#21]
I just spend the last few hours trying to figure out why my cards were not moving:

Fix:
The BoardRepository's `data.id` must be exactly like given in the example : like 1,2,3,4,5....and not some random number.

I had to go through the whole code just to figure that out. Can you pls add a note in the docs mentioning that. Thx.

Great library. Saved me a lot of work. Respect!

**Comment by TacticCoder** [comment]
README updated.
