### ISSUE TITLE
Ipad Compatibles

### ISSUE THREAD

**Issue by mahipalsingh-syt** [bear-junior/react-native-draganddrop-board#24]
Cards are not compatible with ipad/tablets

**Comment by TacticCoder** [comment]
Can you send some pictures?

**Comment by mahipalsingh-syt** [comment]
> Can you send some pictures?

@TacticCoder 
Dashboard is showing compatibility but when i drag Card between columns its expand in full size.

<img width="534" alt="Screenshot 2020-12-14 at 8 27 12 PM" src="https://user-images.githubusercontent.com/64964760/102096689-fdb60a80-3e4a-11eb-9e56-bd1da6095820.png">

<img width="544" alt="Screenshot 2020-12-14 at 8 27 22 PM" src="https://user-images.githubusercontent.com/64964760/102096698-03135500-3e4b-11eb-83d9-021256884961.png">

**Comment by TacticCoder** [comment]
probably a style problem, PR soon

**Comment by mahipalsingh-syt** [comment]
> probably a style problem, PR soon
@TacticCoder 
i already made some change on my repo... but when i fixed the width of card, the dragging functionality would not work .

https://github.com/mahipalsingh-syt/react-native-draganddrop-board.git

**Comment by TacticCoder** [comment]
Link here the changes please

**Comment by TacticCoder** [comment]
Can you link me to your changes ?

**Comment by mahipalsingh-syt** [comment]
> Can you link me to your changes ?
https://github.com/bear-junior/react-native-draganddrop-board/pull/25

you can find the changes in this PR... i'll resolve Conflicts later

@TacticCoder

**Comment by TacticCoder** [comment]
#25 PR Approved, can we close this issue?
