### ISSUE TITLE
TypeError: styled_components__WEBPACK_IMPORTED_MODULE_1__.default.View is not a function

### ISSUE THREAD

**Issue by draczer01** [bear-junior/react-native-draganddrop-board#5]
I get this error while trying to run the app using react native for web, the error only happens with the "w" option in expo, android and ios work fine

×
TypeError: styled_components__WEBPACK_IMPORTED_MODULE_1__.default.View is not a function
../../../../../../../../../../../react-native-apps/test1/testing/node_modules/react-native-draganddrop-board/src/components/EmptyColumn/EmptyColumn.styled.js
http://172.17.1.155:19006/static/js/bundle.js:79981:78
__webpack_require__
http://172.17.1.155:19006/static/js/bundle.js:727:30
fn
/react-native-apps/test1/testing/screens/LinksScreen.js:96

```
  93 | cardContent={(item) => (<View>
  94 | 
  95 |   <Text>{item.name}</Text>
> 96 |   <Text>{item.description}</Text>
     | ^  97 |   <Text></Text>
  98 | 
  99 |   <TouchableHighlight

```
fn
/react-native-apps/test1/testing/screens/LinksScreen.js:96
```

  93 | cardContent={(item) => (<View>
  94 | 
  95 |   <Text>{item.name}</Text>
> 96 |   <Text>{item.description}</Text>
     | ^  97 |   <Text></Text>
  98 | 
  99 |   <TouchableHighlight
```

fn
/react-native-apps/test1/testing/screens/LinksScreen.js:96

```
  93 | cardContent={(item) => (<View>
  94 | 
  95 |   <Text>{item.name}</Text>
> 96 |   <Text>{item.description}</Text>
     | ^  97 |   <Text></Text>
  98 | 
  99 |   <TouchableHighlight
```

fn
/react-native-apps/test1/testing/screens/LinksScreen.js:96

```
  93 | cardContent={(item) => (<View>
  94 | 
  95 |   <Text>{item.name}</Text>
> 96 |   <Text>{item.description}</Text>
     | ^  97 |   <Text></Text>
  98 | 
  99 |   <TouchableHighlight
```

fn
/react-native-apps/test1/testing/screens/LinksScreen.js:96
```

  93 | cardContent={(item) => (<View>
  94 | 
  95 |   <Text>{item.name}</Text>
> 96 |   <Text>{item.description}</Text>
     | ^  97 |   <Text></Text>
  98 | 
  99 |   <TouchableHighlight
```

fn
/react-native-apps/test1/testing/screens/LinksScreen.js:96
```

  93 | cardContent={(item) => (<View>
  94 | 
  95 |   <Text>{item.name}</Text>
> 96 |   <Text>{item.description}</Text>
     | ^  97 |   <Text></Text>
  98 | 
  99 |   <TouchableHighlight
```

fn
/react-native-apps/test1/testing/screens/LinksScreen.js:96

```
  93 | cardContent={(item) => (<View>
  94 | 
  95 |   <Text>{item.name}</Text>
> 96 |   <Text>{item.description}</Text>
     | ^  97 |   <Text></Text>
  98 | 
  99 |   <TouchableHighlight

```
fn
/react-native-apps/test1/testing/screens/LinksScreen.js:96

```
  93 | cardContent={(item) => (<View>
  94 | 
  95 |   <Text>{item.name}</Text>
> 96 |   <Text>{item.description}</Text>
     | ^  97 |   <Text></Text>
  98 | 
  99 |   <TouchableHighlight
```

fn
/react-native-apps/test1/testing/screens/LinksScreen.js:96

```
  93 | cardContent={(item) => (<View>
  94 | 
  95 |   <Text>{item.name}</Text>
> 96 |   <Text>{item.description}</Text>
     | ^  97 |   <Text></Text>
  98 | 
  99 |   <TouchableHighlight
```

fn
/react-native-apps/test1/testing/screens/LinksScreen.js:96
```

  93 | cardContent={(item) => (<View>
  94 | 
  95 |   <Text>{item.name}</Text>
> 96 |   <Text>{item.description}</Text>
     | ^  97 |   <Text></Text>
  98 | 
  99 |   <TouchableHighlight

```
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by draczer01** [comment]
I just fixed this in a pull request

**Comment by nicolassanmar** [comment]
Im having this exact same problem, maybe an update caused this?

Uncaught TypeError: styled_components__WEBPACK_IMPORTED_MODULE_1__.default.View is not a function
