### ISSUE TITLE
improper react native web display and functionality

### ISSUE THREAD

**Issue by draczer01** [bear-junior/react-native-draganddrop-board#9]
when used in react native web the the columns are too wide, the cards become transparent and only the cards in the first column are draggable, at first, but once one card gets dragged the other cards on the rest of the columns become draggable but the cards in the first column become undraggable.
the shades are displayed incorrectly and the circle behind the card count disapears

Edit: looks like the problem exists because only the cards in the selected column are movable, looks like this may require platform specific code

**Comment by TacticCoder** [comment]
Your #6 PR committed.
